source "virtualbox-iso" "autogenerated_1" {
  boot_command         = [
    "<enter>", 
    "<wait20s>", 
    // "sudo /usr/bin/coreos-installer install -I ${var.ignition_url} ${var.ignition_hash} -u ${var.raw_url} --insecure /dev/sda", 
    "sudo /usr/bin/coreos-installer install -I http://{{ .HTTPIP }}:{{ .HTTPPort }}/${var.ignition_url} ${var.ignition_hash} -u http://{{ .HTTPIP }}:{{ .HTTPPort }}/${var.raw_url} --insecure /dev/sda", 
    "<enter>", 
    "<wait1m>", 
    "reboot", 
    "<enter>", 
    "<wait30s>"
  ]
  boot_wait            = "5s"
  iso_checksum         = "sha256:${var.iso_checksum}"
  guest_os_type        = "RedHat8_64"
  http_directory       = "http"
  iso_url              = "${var.iso_url}"
  guest_additions_mode = "${var.guest_additions}"
  guest_additions_path = "VBoxGuestAdditions_{{ .Version }}.iso"
  memory               = 3072
  shutdown_command     = "sudo /sbin/shutdown -P -h now"
  ssh_private_key_file = "id_rsa"
  ssh_username         = "core"
  vboxmanage = [
    [ "modifyvm", "{{.Name}}", "--nat-localhostreachable1", "on"], // Virtualbox v7 compatibility issue with packer v1.8.5 https://github.com/hashicorp/packer/issues/12118
  ]
  virtualbox_version_file = ".vbox_version"
}

build {
  sources = ["source.virtualbox-iso.autogenerated_1"]

  provisioner "shell" {
    execute_command = "echo 'packer'|{{ .Vars }} sudo -S -E bash '{{ .Path }}'"

    environment_vars = ["guest_additions_mode=${var.guest_additions}"]
    scripts         = [
      "scripts/90virtualbox.sh",
      "scripts/99minimize.sh"
    ]
  }

  post-processor "vagrant" {
    compression_level = 9
    output            = "redhat-coreos.box"
  }
}