Vagrant.configure("2") do |config|
	config.vm.box = "rhcos"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
		vb.cpus = 2
	end
	config.ssh.username = "core"
	config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vm.synced_folder ".", "/var/home/core/host-synced-folder"
end